___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1


#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [67]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [153]:

print("Version:", np.__version__)

Version: 1.23.5


In [158]:
print(np.show_config())

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

Створити вектор з 10 елементів, заповнений одиницями:

In [70]:
v = np.ones(10)
v

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [71]:
v = np.arange(0, 11)
v

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [72]:
m = np.zeros((5, 5))
m

array([[0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [73]:
np.random.seed(42)
v = np.random.randint(20, size = (1, 20))
v

array([[ 6, 19, 14, 10, 7, 6, 18, 10, 10, 3, 7, 2, 1, 11, 5, 1,
 0, 11, 11, 16]])

In [74]:
indices = np.nonzero(v)
print(f"Indices of non-zero elements are in this array:\n {indices}")

Indices of non-zero elements are in this array:
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17,
       18, 19]))


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [75]:
print(f"Mean value for vector `v`: {v.mean()}")
print(f"Median for vector `v`: {np.median(v)}")
print(f"Standard deviation for vector `v`: {np.std(v)}")

Mean value for vector `v`: 8.4
Median for vector `v`: 8.5
Standard deviation for vector `v`: 5.471745608121781


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [76]:
#first matrix
np.random.seed(42)
m1 = np.random.randint(1, 10, (4, 2))
m1

array([[7, 4],
 [8, 5],
 [7, 3],
 [7, 8]])

In [77]:
#second matrix
np.random.seed(42)
m2 = np.random.randint(100, 120, (2, 2))
m2

array([[106, 119],
 [114, 110]])

In [78]:
#to multiply
m1m2 = np.dot(m1, m2)
m1m2

array([[1198, 1273],
 [1418, 1502],
 [1084, 1163],
 [1654, 1713]])

Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [79]:
#to create a vector
vm1m2 = m1m2.ravel()
vm1m2

array([1198, 1273, 1418, 1502, 1084, 1163, 1654, 1713])

In [80]:
#to find min and max of the resulting vector
print(f"Min of vm1m2: {vm1m2.min()}")
print(f"Max of vm1m2: {vm1m2.max()}")

Min of vm1m2: 1084
Max of vm1m2: 1713


In [81]:
#to substitute the max of the vector by zero
max_ = vm1m2.max()
vm1m2[vm1m2 == max_] = 0
vm1m2

array([1198, 1273, 1418, 1502, 1084, 1163, 1654, 0])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [114]:
#the matrix from the previous task
m1m2

array([[1198, 1273],
 [1418, 1502],
 [1084, 1163],
 [1654, 0]])

In [131]:
#to calculate the correlation between the first row and all other rows of the matrix
coeffs = np.corrcoef(m1m2[0], m1m2[1:])
coeffs

array([[ 1., 1., 1., -1.],
 [ 1., 1., 1., -1.],
 [ 1., 1., 1., -1.],
 [-1., -1., -1., 1.]])

Дано матрицю. Знайти ранг матриці:

In [162]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [163]:
from numpy import linalg

rank = np.linalg.matrix_rank(a)
print(f"The rank of the matrix `a` is: {rank}")

The rank of the matrix `a` is: 3


Знайти визначник матриці:

In [164]:
determinant = linalg.det(a)
print(f"The determinant of the matrix `a` is: {determinant}")

The determinant of the matrix `a` is: 440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [179]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues, eigenvectors) 

[14.13520334+0.j         -4.56760167+3.20389947j -4.56760167-3.20389947j] [[ 0.43131913+0.j         -0.31386258-0.47450898j -0.31386258+0.47450898j]
 [ 0.41502436+0.j         -0.07049527+0.4090732j  -0.07049527-0.4090732j ]
 [ 0.8010734 +0.j          0.7099444 +0.j          0.7099444 -0.j        ]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [180]:
a = np.random.randint(0,10,50)
a

array([7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5, 4, 1, 7, 5, 1, 4, 0, 9, 5,
 8, 0, 9, 2, 6, 3, 8, 2, 4, 2, 6, 4, 8, 6, 1, 3, 8, 1, 9, 8, 9, 4,
 1, 3, 6, 7, 2, 0])

In [186]:
print("Number with the highest frequency in `a`:", np.bincount(a).argmax())

Number with the highest frequency in `a`: 4


Виведіть лише парні числа, що діляться на 5:

In [206]:
a = np.random.randint(0,10,50)
a

array([7, 0, 5, 3, 0, 6, 8, 3, 3, 5, 2, 5, 6, 9, 9, 2, 6, 2, 1, 9, 3, 7,
 8, 6, 0, 2, 8, 0, 8, 7, 0, 5, 4, 5, 9, 4, 5, 4, 4, 3, 2, 2, 3, 8,
 1, 8, 0, 0, 4, 5])

In [214]:
even_numbers = [i for i in list(a) if i%5 == 0 if i%2 ==0]
print("Even numbers from `a` which are divisible by `5`:", even_numbers)

Even numbers from `a` which are divisible by `5`: [0, 0, 0, 0, 0, 0, 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [211]:
first_eq = np.array([[2, 5], [1, -10]])
second_eq = np.array([1, 3])

res = np.linalg.solve(first_eq, second_eq)
print("x, y:")
print(res)

x, y:
[ 1.  -0.2]


In [213]:
# To check the solution
np.allclose(np.dot(first_eq, res), second_eq)

True